---

- name: Get admin context
  shell: kubectl config view -o=jsonpath='{range .contexts[*]}{.name}{"\n"}{end}}' | grep system
  register: okd_admin_context

- name: Get admin user
  shell: kubectl config view -o=jsonpath='{range .users[*]}{.name}{"\n"}{end}}' | grep system
  register: okd_admin_user

- name: Get cluster name
  shell: kubectl config view -o=jsonpath='{range .clusters[*]}{.name}{"\n"}{end}}' | grep 8443
  register: okd_cluster_name

- name: Temporarily use admin context
  command: kubectl config use-context {{ okd_admin_context.stdout }}
  when: okd_admin_context is succeeded

- name: create the namespace benchmark
  command: kubectl create namespace benchmark
  ignore_errors: yes

- name: set to admin context
  command: kubectl config set-context ripsaw --namespace=benchmark --cluster={{ okd_cluster_name.stdout }} --user={{ okd_admin_user.stdout }}
  register: ripsaw_context
  when: okd_admin_user is succeeded and okd_cluster_name is succeeded

- name: use ripsaw context
  command: kubectl config use-context ripsaw
  when: ripsaw_context is succeeded
