---

- name: Get root partition volume name
  shell: cat /etc/fstab | grep " / " | cut -d' ' -f1
  register: root_partition

- name: resize root partition
  command: lvextend -r {{ root_partition.stdout }} -L {{ lvm_root_size }}
  when: root_partition is succeeded
